language: node_js
node_js:

  - "6"
  - "6.1"
  - "5.11"


branches:
  only:
    - gh-pages

before_script:
  - npm install -g firebase-tools

script:
  - jasmine test.js


after_success:
   - firebase deploy




